spring:
  application:
    name: gateway
  redis:
    port: 6379
    password: 123456
    host: localhost
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: wms-user
          uri: lb://wms-user-service
          predicates:
            - Path=/wms/user/**
        - id: wms-admin-manager
          uri: lb://wms-admin-manager-service
          predicates:
            - Path=/wms/admin-manager/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8888"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wms_db?serverTimezone=UTC&userSSL=false
      username: root
      password: 123456
server:
  port: 10010