server:
  port: 9090
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: wms-admin-manager-service
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wms_db?serverTimezone=UTC&userSSL=false
      username: root
      password: 123456
  redis:
    port: 6379
    password: 123456
    host: localhost
logging:
  level:
    com:
      hnkj:
        mapper: debug
        service: info
        controller: info
mybatis:
  type-aliases-package: com.hnkj.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql